### ISSUE TITLE
Allow Elytra to go faster when descending

### ISSUE THREAD

**Issue by sleepylessons** [crimenoodle/WildAnarchy#47]
**Describe the bug**
When descending, Elytras can go faster than 45bps (vanilla). We should honor this choice by Mojang and allow this to work.

**To Reproduce**
- Use vanilla Elytra with rockets
- Go up high
- Begin descending
- If you have a strong angle of attack with the ground, you will go faster than 45bps and be lagged back by speed limit

**Comment by sleepylessons** [comment]
I have added some new functionality to Elytra based speed limit:


```yml
tracking:
  # How many locations should we store per-player
  location-cache-count: 3
  # Elytra-specific Settings
  elytra:
    # How many ticks after landing should a player retain the elytra speed limit (prevents lagbacks from landing)
    grace-period: 20
    # Whether elytra speed limit should be increased when the player is descending
    can-descend-faster: true
    # What should be the max Rate of Descent that can be used in calculations to increase speed limit (blocks per second)
    max-rate-of-descent: 40
    # Used in speed increase calculations; (elytra-speed-limit + (rate-of-descent * rate-of-descent-multiplier))
    rate-of-descent-multiplier: 1.8
    # Absolute max speed limit we will allow even for the fastest descents (in blocks per second)
    absolute-max-speed: 75
    # The max Y level that speed multipliers will work under; prevents players going straight up
    # for a long time to get very long bouts of higher speed
    max-descent-height: 320
```

Basically we cache a few locations to track the Y level of the player. If they are steadily descending, we do a calculation with their rate-of-descent & the rate-of-descent-multiplier to add a higher limit to their max speed limit.

This is configurable and therefore should be easy to tweak to ensure that players get lagged back as little as possible when they're not supposed to. We also have hard max limits on their rate-of-descent and max speed, as well as a max height; under which they are entitled to this bonus speed bump.

This way, we can put a cap on abuse, and prevent people from going up 3000 blocks to get a huge speed bump which they could abuse with clients.
