### ISSUE TITLE
Allow players to airplace non-pvp related blocks

### ISSUE THREAD

**Issue by sleepylessons** [crimenoodle/WildAnarchy#48]
**Is your feature request related to a problem? Please describe.**
Airplace is viewed as a QOL feature for a lot of builders, and I don't see much point in blocking it if they can't abuse it too much in PVP. This is our goal always, to balance the two main aspects of playing Anarchy.

**Describe the solution you'd like**
We should add a configurable list of block types that can't be airplaced, such as TNT, Obsidian, Beds, etc. The rest we will allow to pass without issue.

**Describe alternatives you've considered**
Just disabling airplace all together, but the community hates this & I don't see a reason to block them from doing something that doesn't give them an OP advantage in gameplay.

**Comment by sleepylessons** [comment]
I forked NCP and added the following config option to Airplace settings (they call it "against")

```yml
against:
      active: true # already existed
      actions: cancel # already existed
      blacklist: # my new config section
      - OBSIDIAN
      - CRYING_OBSIDIAN
      - NETHERITE_BLOCK
      - TNT
      - ANCIENT_DEBRIS
      - WHITE_BED
      - ORANGE_BED
      - MAGENTA_BED
      - LIGHT_BLUE_BED
      - YELLOW_BED
      - LIME_BED
      - PINK_BED
      - GRAY_BED
      - LIGHT_GRAY_BED
      - CYAN_BED
      - PURPLE_BED
      - BLUE_BED
      - BROWN_BED
      - GREEN_BED
      - RED_BED
      - BLACK_BED
      - RESPAWN_ANCHOR
```
